name: dart_frog_jwt_neon
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dart_frog_auth: ^1.2.0
  dart_jsonwebtoken: ^3.2.0
  logger: ^2.6.0
  postgres: ^3.5.6
  uuid: ^4.5.1

dev_dependencies:
  json_serializable: ^6.9.5
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
