// ignore_for_file: public_member_api_docs

import 'package:uuid/uuid.dart';

class User {
  User({
    required this.username,
    required this.password,
    required this.createdAt,
    required this.updatedAt,
    this.id, // ID is typically auto-generated by DB for new records
    String? uid,
  }) {
    this.uid = uid ?? const Uuid().v4();
  }

  User.fromJson(Map<String, dynamic> json) {
    username = json['username'] as String;
    password = json['password'] as String;
    createdAt = json['created_at'].toString();
    updatedAt = json['updated_at'].toString();
    uid = json['uid'] as String;
    id = json['id'] as int?;
  }
  String? username;
  String? password;
  String? createdAt;
  String? updatedAt;
  String? uid;
  int? id; // Database Primary Key (SERIAL)

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (id != null) {
      data['id'] = id; // Include ID if it exists (for existing users)
    }
    data['username'] = username;
    data['password'] = password;
    data['created_at'] = createdAt.toString();
    data['updated_at'] = updatedAt.toString();
    data['uid'] = uid;
    return data;
  }
}
